### ISSUE TITLE
Work with IPVLAN ?

### ISSUE THREAD

**Issue by enzofrnt** [SickHub/docker-cups-airprint#46] opened 2022-08-14 19:47 UTC
I'm using IPVLAN, does it work with it ?

**Comment by DrPsychick** [comment] 2022-08-14 20:14
I'm not sure, I haven't tried. Looks like it should be possible. Give it a shot and let me know if/how it works then I'll add that to the readme.

**Comment by PIORIGIN** [comment] 2022-08-14 22:05
nice, notif me when you make it and after i can try ^^

**Comment by viperk1** [comment] 2023-11-27 04:06
I can confirm this works with IPVLAN no problem

**Comment by DrPsychick** [comment] 2023-12-29 23:42
@viperk1 @enzofrnt do you want to briefly share for the afterworld what you've done to make it work with IPVLAN, before I close this issue?

**Comment by viperk1** [comment] 2023-12-30 00:46
> @viperk1 @enzofrnt do you want to briefly share for the afterworld what you've done to make it work with IPVLAN, before I close this issue?

Nothing special at all. I just followed your instructions but the network was ipvlan instead of macvlan. 

Here’s my docker compose for the container. “physicalnet” is defined externally as an ipvlan network. 

`
services:
  airprint:
    container_name: airprint
    hostname: airprint.host.name
    image: 'drpsychick/airprint-bridge:latest'
    restart: unless-stopped
    networks:
      physicalnet:
        ipv4_address: 192.168.192.168
    volumes:
        - airprint/cups:/etc/cups
    environment:
        - CUPS_USER_ADMIN=meow
        - CUPS_USER_PASSWORD=meow`

**Comment by DrPsychick** [comment] 2023-12-30 13:57
Awesome, thanks for sharing, in the name of the community!

**Closed by DrPsychick** 2023-12-30 13:57 UTC
